# Generated by Django 4.1.1 on 2022-11-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='passwordmanager',
            name='private_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='password_manager.privatekey'),
        ),
    ]
