# Generated by Django 4.1.1 on 2022-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordmanager',
            name='icon_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
