# Generated by Django 4.1.1 on 2022-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_passwordmanager_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='icon_name',
            field=models.CharField(max_length=255),
        ),
    ]
