# Generated by Django 4.1.1 on 2022-11-05 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_manager', '0002_privatekey_passwordmanager_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmanager',
            name='private_key',
        ),
        migrations.AddField(
            model_name='privatekey',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
