# Generated by Django 4.1.1 on 2022-11-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0003_remove_passwordmanager_private_key_privatekey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='salt',
            field=models.BinaryField(default=None),
        ),
    ]
