# Generated by Django 4.1.1 on 2022-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0004_privatekey_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='salt',
            field=models.BinaryField(),
        ),
    ]
